# Looking for the best Formula 1 season

For my master's project, I'm making a piece about answering the question: **What championship winning team had the best Formula 1 season?**

To answer this question, I'll be checking three definitions of best:

1. most wins in a season
1. most podiums in a season
1. how close was the performance to perfect

To do this I was working with data provided by the [Ergast Developer API](https://ergast.com/mrd/). I noticed an error in the driver-constructor pairing for the 1950 season and wanted to verify things without moving forward. I was originally going to create a table of the driver-constructor pairs for each race, and then compare it with the data I had.

Instead I went straight to the source for F1 information, [formula1.com](https://formula1.com), and scraped race information for each race from 1950 to 2018. There were some holes with how disqualifications and withdrawal were recorded (or not, in this case) as we went back in time to earlier seasons.

Now I've gone and gotten data from [statsf1.com](https://www.statsf1.com/) which is tabulated in an easy to understand manner and is more complete than the formula1.com data.

In [1]:
import pandas as pd
import numpy as np

In [38]:
# race_results = pd.read_csv("../data/from_scripts/statsf1_race_results.csv")
race_results = pd.read_csv("../data/other/statsf1_race_results_v2.csv")

In [39]:
race_results.head(30)

,result_id,race_id,year,round,race_name,position,p0,driver,team,constructor_long,extra
0,1,1,1950,1,Britain,1,1,Giuseppe FARINA,Alfa Romeo,Alfa Romeo Alfa Romeo,2h 13m 23.6s ( 146.378 km/h )
1,2,1,1950,1,Britain,2,2,Luigi FAGIOLI,Alfa Romeo,Alfa Romeo Alfa Romeo,2h 13m 26.2s ( +02.6s )
2,3,1,1950,1,Britain,3,3,Reg PARNELL,Alfa Romeo,Alfa Romeo Alfa Romeo,2h 14m 15.6s ( +52.0s )
3,4,1,1950,1,Britain,4,4,Yves GIRAUD-CABANTOUS,Talbot Lago,Talbot Lago Talbot,
4,5,1,1950,1,Britain,5,5,Louis ROSIER,Talbot Lago,Talbot Lago Talbot,
5,6,1,1950,1,Britain,6,6,Bob GERARD,ERA,ERA ERA,
6,7,1,1950,1,Britain,7,7,Cuth HARRISON,ERA,ERA ERA,
7,8,1,1950,1,Britain,8,8,Philippe ETANCELIN,Talbot Lago,Talbot Lago Talbot,
8,9,1,1950,1,Britain,9,9,David HAMPSHIRE,Maserati,Maserati Maserati,
9,10,1,1950,1,Britain,10,10,Joe FRY,Maserati,Maserati Maserati,
10,11,1,1950,1,Britain,&,10,Brian SHAWE-TAYLOR,NaN,,
11,12,1,1950,1,Britain,11,11,Johnny CLAES,Talbot Lago,Talbot Lago Talbot,
12,13,1,1950,1,Britain,ab,12,Juan Manuel FANGIO,Alfa Romeo,Alfa Romeo Alfa Romeo,Oil line
13,14,1,1950,1,Britain,nc,13,Joe KELLY,Alta,Alta Alta,
14,15,1,1950,1,Britain,ab,14,Prince BIRA,Maserati,Maserati Maserati,Fuel injection
15,16,1,1950,1,Britain,ab,15,David MURRAY,Maserati,Maserati Maserati,Engine
16,17,1,1950,1,Britain,ab,16,Geoff CROSSLEY,Alta,Alta Alta,Transmission
17,18,1,1950,1,Britain,ab,17,Emmanuel de GRAFFENRIED,Maserati,Maserati Maserati,Connecting rod
18,19,1,1950,1,Britain,ab,18,Louis CHIRON,Maserati,Maserati Maserati,Clutch
19,20,1,1950,1,Britain,ab,19,Eugène MARTIN,Talbot Lago,Talbot Lago Talbot,Oil pressure
20,21,1,1950,1,Britain,ab,20,Peter WALKER,ERA,ERA ERA,
21,22,1,1950,1,Britain,&,20,Tony ROLT,NaN,,Gearbox
22,23,1,1950,1,Britain,ab,21,Leslie JOHNSON,ERA,ERA ERA,Supercharger
23,24,1,1950,1,Britain,f,22,Felice BONETTO,Maserati Milano,Maserati Milano Maserati,Not present
24,25,1,1950,1,Britain,f,23,Raymond MAYS,ERA,ERA ERA,Entry cancelled
25,26,2,1950,2,Monaco,1,1,Juan Manuel FANGIO,Alfa Romeo,Alfa Romeo Alfa Romeo,3h 13m 18.7s ( 98.701 km/h )
26,27,2,1950,2,Monaco,2,2,Alberto ASCARI,Ferrari,Ferrari Ferrari,
27,28,2,1950,2,Monaco,3,3,Louis CHIRON,Maserati,Maserati Maserati,
28,29,2,1950,2,Monaco,4,4,Raymond SOMMER,Ferrari,Ferrari Ferrari,
29,30,2,1950,2,Monaco,5,5,Prince BIRA,Maserati,Maserati Maserati,

Let's verify that we have the right number of races. Between 1950 and the end of the 2018 season there were 997 races.

In [40]:
race_results.race_id.max()

997

Before we get to analysis, there is some processing that needs to be done. First I want to fill in the teams.

In [41]:
def update_teams(row):
    df = race_results
    if row.position == "&":
        return df.team.shift(-1)[0]
    else:
        return row.team
    
def update_constructor_long(row):
    df = race_results
    if row.position == "&":
        return df.constructor_long.shift(-1)[0]
    else:
        return row.constructor_long

In [42]:
race_results["team"] = race_results.apply(update_teams, axis=1)
race_results["constructor_long"] = race_results.apply(update_teams, axis = 1)

In [43]:
race_results.head(30)

,result_id,race_id,year,round,race_name,position,p0,driver,team,constructor_long,extra
0,1,1,1950,1,Britain,1,1,Giuseppe FARINA,Alfa Romeo,Alfa Romeo,2h 13m 23.6s ( 146.378 km/h )
1,2,1,1950,1,Britain,2,2,Luigi FAGIOLI,Alfa Romeo,Alfa Romeo,2h 13m 26.2s ( +02.6s )
2,3,1,1950,1,Britain,3,3,Reg PARNELL,Alfa Romeo,Alfa Romeo,2h 14m 15.6s ( +52.0s )
3,4,1,1950,1,Britain,4,4,Yves GIRAUD-CABANTOUS,Talbot Lago,Talbot Lago,
4,5,1,1950,1,Britain,5,5,Louis ROSIER,Talbot Lago,Talbot Lago,
5,6,1,1950,1,Britain,6,6,Bob GERARD,ERA,ERA,
6,7,1,1950,1,Britain,7,7,Cuth HARRISON,ERA,ERA,
7,8,1,1950,1,Britain,8,8,Philippe ETANCELIN,Talbot Lago,Talbot Lago,
8,9,1,1950,1,Britain,9,9,David HAMPSHIRE,Maserati,Maserati,
9,10,1,1950,1,Britain,10,10,Joe FRY,Maserati,Maserati,
10,11,1,1950,1,Britain,&,10,Brian SHAWE-TAYLOR,Alfa Romeo,Alfa Romeo,
11,12,1,1950,1,Britain,11,11,Johnny CLAES,Talbot Lago,Talbot Lago,
12,13,1,1950,1,Britain,ab,12,Juan Manuel FANGIO,Alfa Romeo,Alfa Romeo,Oil line
13,14,1,1950,1,Britain,nc,13,Joe KELLY,Alta,Alta,
14,15,1,1950,1,Britain,ab,14,Prince BIRA,Maserati,Maserati,Fuel injection
15,16,1,1950,1,Britain,ab,15,David MURRAY,Maserati,Maserati,Engine
16,17,1,1950,1,Britain,ab,16,Geoff CROSSLEY,Alta,Alta,Transmission
17,18,1,1950,1,Britain,ab,17,Emmanuel de GRAFFENRIED,Maserati,Maserati,Connecting rod
18,19,1,1950,1,Britain,ab,18,Louis CHIRON,Maserati,Maserati,Clutch
19,20,1,1950,1,Britain,ab,19,Eugène MARTIN,Talbot Lago,Talbot Lago,Oil pressure
20,21,1,1950,1,Britain,ab,20,Peter WALKER,ERA,ERA,
21,22,1,1950,1,Britain,&,20,Tony ROLT,Alfa Romeo,Alfa Romeo,Gearbox
22,23,1,1950,1,Britain,ab,21,Leslie JOHNSON,ERA,ERA,Supercharger
23,24,1,1950,1,Britain,f,22,Felice BONETTO,Maserati Milano,Maserati Milano,Not present
24,25,1,1950,1,Britain,f,23,Raymond MAYS,ERA,ERA,Entry cancelled
25,26,2,1950,2,Monaco,1,1,Juan Manuel FANGIO,Alfa Romeo,Alfa Romeo,3h 13m 18.7s ( 98.701 km/h )
26,27,2,1950,2,Monaco,2,2,Alberto ASCARI,Ferrari,Ferrari,
27,28,2,1950,2,Monaco,3,3,Louis CHIRON,Maserati,Maserati,
28,29,2,1950,2,Monaco,4,4,Raymond SOMMER,Ferrari,Ferrari,
29,30,2,1950,2,Monaco,5,5,Prince BIRA,Maserati,Maserati,

Now we can look at processing the finishing order.  In scraping I had created a rough version of the final order, but now I want to refine it more.

The position column gives us information about how the driver fared in the race. There are several options:

* If the position is a number (in string form or otherwise) then that is the finishing position of the driver.
* If the position is `&` then that driver record is for a shared drive and the finishing position of that driver is the same as the record directly above it.
* If the position is `ab` then the driver retired. We will try two different interpretations: *leave the order as is* and, *change all the retired orders to the retired order for the race.*
* IF the position is `nc` the driver did not classify for the final positions, so we can make that the average of the retired drivers as well.
* If the position is `f` then the driver withdrew from a race. They will ranked as the last possible spot.
* If the position is `np` then the driver did not star the race, but was on the grid. They will be ranked as the last possible spot.
* If the position is `dsq`, the driver was disqualified and their finishing position will be the the last possible spot.
* If the position is `npq`, `nq`, or `exc` the driver's order will be ignored. 
* If the position is `tf` do nothing.

We'll do it in two parts, first updating everything but the shared drives.

In [51]:
def p1(row):
    race = race_results[race_results.race_id == row.race_id]
    last_place = race.p0.max()
    avg_retire = np.round(race[race.position.isin(["ab", "nc"])].p0.mean())
    
    if (row.position == "dsq") or (row.position == "f") or (row.position == "np"):
        return last_place
    elif (row.position == "ab") or (row.position == "nc"):
        return avg_retire
    else:
        return row.p0
    
def update_p1(row):
    race = race_results[race_results.race_id == row.race_id]
    if row.position == "&":
        return race.p1.shift(1)
    else:
        return row.p1

shared_drives = race_results.index[race_results.position == "&"].tolist()
def p_1(row):
    prev = race_results.iloc[row.name -1]
    if row.name in shared_drives:
        return True
    else:
        return False

In [52]:
# race_results["p1"] = race_results.apply(p1, axis =1)
# race_results["p1_v2"] = race_results.apply(update_p1, axis=1)
race_results["p_1"] = race_results.apply(p_1, axis=1)

In [53]:
race_results.head(30)

,result_id,race_id,year,round,race_name,position,p0,driver,team,constructor_long,extra,p_1
0,1,1,1950,1,Britain,1,1,Giuseppe FARINA,Alfa Romeo,Alfa Romeo,2h 13m 23.6s ( 146.378 km/h ),False
1,2,1,1950,1,Britain,2,2,Luigi FAGIOLI,Alfa Romeo,Alfa Romeo,2h 13m 26.2s ( +02.6s ),False
2,3,1,1950,1,Britain,3,3,Reg PARNELL,Alfa Romeo,Alfa Romeo,2h 14m 15.6s ( +52.0s ),False
3,4,1,1950,1,Britain,4,4,Yves GIRAUD-CABANTOUS,Talbot Lago,Talbot Lago,,False
4,5,1,1950,1,Britain,5,5,Louis ROSIER,Talbot Lago,Talbot Lago,,False
5,6,1,1950,1,Britain,6,6,Bob GERARD,ERA,ERA,,False
6,7,1,1950,1,Britain,7,7,Cuth HARRISON,ERA,ERA,,False
7,8,1,1950,1,Britain,8,8,Philippe ETANCELIN,Talbot Lago,Talbot Lago,,False
8,9,1,1950,1,Britain,9,9,David HAMPSHIRE,Maserati,Maserati,,False
9,10,1,1950,1,Britain,10,10,Joe FRY,Maserati,Maserati,,False
10,11,1,1950,1,Britain,&,10,Brian SHAWE-TAYLOR,Alfa Romeo,Alfa Romeo,,True
11,12,1,1950,1,Britain,11,11,Johnny CLAES,Talbot Lago,Talbot Lago,,False
12,13,1,1950,1,Britain,ab,12,Juan Manuel FANGIO,Alfa Romeo,Alfa Romeo,Oil line,False
13,14,1,1950,1,Britain,nc,13,Joe KELLY,Alta,Alta,,False
14,15,1,1950,1,Britain,ab,14,Prince BIRA,Maserati,Maserati,Fuel injection,False
15,16,1,1950,1,Britain,ab,15,David MURRAY,Maserati,Maserati,Engine,False
16,17,1,1950,1,Britain,ab,16,Geoff CROSSLEY,Alta,Alta,Transmission,False
17,18,1,1950,1,Britain,ab,17,Emmanuel de GRAFFENRIED,Maserati,Maserati,Connecting rod,False
18,19,1,1950,1,Britain,ab,18,Louis CHIRON,Maserati,Maserati,Clutch,False
19,20,1,1950,1,Britain,ab,19,Eugène MARTIN,Talbot Lago,Talbot Lago,Oil pressure,False
20,21,1,1950,1,Britain,ab,20,Peter WALKER,ERA,ERA,,False
21,22,1,1950,1,Britain,&,20,Tony ROLT,Alfa Romeo,Alfa Romeo,Gearbox,True
22,23,1,1950,1,Britain,ab,21,Leslie JOHNSON,ERA,ERA,Supercharger,False
23,24,1,1950,1,Britain,f,22,Felice BONETTO,Maserati Milano,Maserati Milano,Not present,False
24,25,1,1950,1,Britain,f,23,Raymond MAYS,ERA,ERA,Entry cancelled,False
25,26,2,1950,2,Monaco,1,1,Juan Manuel FANGIO,Alfa Romeo,Alfa Romeo,3h 13m 18.7s ( 98.701 km/h ),False
26,27,2,1950,2,Monaco,2,2,Alberto ASCARI,Ferrari,Ferrari,,False
27,28,2,1950,2,Monaco,3,3,Louis CHIRON,Maserati,Maserati,,False
28,29,2,1950,2,Monaco,4,4,Raymond SOMMER,Ferrari,Ferrari,,False
29,30,2,1950,2,Monaco,5,5,Prince BIRA,Maserati,Maserati,,False

In [14]:
race_results[race_results.race_id == 273]

,race_id,year,round,race_name,position,p0,driver,team,constructor_long,extra,p1
7174,273,1976,9,Britain,dsq,-1.0,James HUNT,McLaren,McLaren,Started unofficially 1h 43m 27.61s,28.0
7175,273,1976,9,Britain,1,1.0,Niki LAUDA,Ferrari,Ferrari,1h 44m 19.66s ( 183.881 km/h ),1.0
7176,273,1976,9,Britain,2,2.0,Jody SCHECKTER,Tyrrell,Tyrrell,1h 44m 35.84s ( +16.18s ),2.0
7177,273,1976,9,Britain,3,3.0,John WATSON,Penske,Penske,,3.0
7178,273,1976,9,Britain,4,4.0,Tom PRYCE,Shadow,Shadow,,4.0
7179,273,1976,9,Britain,5,5.0,Alan JONES,Surtees,Surtees,,5.0
7180,273,1976,9,Britain,6,6.0,Emerson FITTIPALDI,Copersucar,Copersucar,,6.0
7181,273,1976,9,Britain,7,7.0,Harald ERTL,Hesketh,Hesketh,,7.0
7182,273,1976,9,Britain,8,8.0,Carlos PACE,Brabham,Brabham,,8.0
7183,273,1976,9,Britain,9,9.0,Jean-Pierre JARIER,Shadow,Shadow,,9.0
7184,273,1976,9,Britain,ab,10.0,Gunnar NILSSON,Lotus,Lotus,Engine,16.0
7185,273,1976,9,Britain,ab,11.0,Ronnie PETERSON,March,March,Fuel pressure,16.0
7186,273,1976,9,Britain,ab,12.0,Brett LUNGER,Surtees,Surtees,Gearbox,16.0
7187,273,1976,9,Britain,ab,13.0,Patrick DEPAILLER,Tyrrell,Tyrrell,Engine,16.0
7188,273,1976,9,Britain,ab,14.0,Carlos REUTEMANN,Brabham,Brabham,Oil pressure,16.0
7189,273,1976,9,Britain,ab,15.0,Arturo MERZARIO,March,March,Engine,16.0
7190,273,1976,9,Britain,dsq,-1.0,Clay REGAZZONI,Ferrari,Ferrari,Changed car,28.0
7191,273,1976,9,Britain,dsq,-1.0,Jacques LAFFITE,Ligier,Ligier,Changed car,28.0
7192,273,1976,9,Britain,ab,16.0,Bob EVANS,Brabham,Brabham,Gearbox,16.0
7193,273,1976,9,Britain,ab,17.0,Vittorio BRAMBILLA,March,March,Suspension,16.0
7194,273,1976,9,Britain,ab,18.0,Henri PESCAROLO,Surtees,Surtees,Fuel pressure,16.0
7195,273,1976,9,Britain,ab,19.0,Chris AMON,Ensign,Ensign,Engine,16.0
7196,273,1976,9,Britain,ab,20.0,Mario ANDRETTI,Lotus,Lotus,Ignition,16.0
7197,273,1976,9,Britain,ab,21.0,Jochen MASS,McLaren,McLaren,Clutch,16.0
7198,273,1976,9,Britain,ab,22.0,Hans Joachim STUCK,March,March,Spin,16.0
7199,273,1976,9,Britain,ab,23.0,Guy EDWARDS,Hesketh,Hesketh,Collision,16.0
7200,273,1976,9,Britain,nq,24.0,Jacky ICKX,Williams,Williams,,24.0
7201,273,1976,9,Britain,nq,25.0,Divina GALICA,Surtees,Surtees,,25.0
7202,273,1976,9,Britain,nq,26.0,Mike WILDS,Shadow,Shadow,,26.0
7203,273,1976,9,Britain,nq,27.0,Lella LOMBARDI,Brabham,Brabham,,27.0
7204,273,1976,9,Britain,f,28.0,Ingo HOFFMANN,Copersucar,Copersucar,Car unavailable,28.0